### ISSUE TITLE
Any way to enable https for flask API?

### ISSUE THREAD

**Issue by fuzzybro** [mhodzic93/tf-flask#1]
Not sure if this repo supports HTTPS config but would be very handy to generate certs and deploy them to ec2 nodes with automatic nginx config

**Comment by mhodzic93** [comment]
@fuzzybro The repo currently does support https and nginx will handle http requests with a redirect to https. The nginx entrypoint currently generates the cert; however, this will be moved to a different spot to allow for the cert to be generated outside of the container and then have the ec2 instance pull it down from S3 and mount it on the container.

**Comment by fuzzybro** [comment]
awesome!
